### ISSUE TITLE
Arbitrary[Map[Int, List[Int]]]: Gave up after only 62 passed tests.

### ISSUE THREAD

**Issue by OlivierBlanvillain** [alexarchambault/scalacheck-shapeless#31]
I've had the following issue on `shapeless-contrib`, which I think also affects `scalacheck-shapeless`: https://github.com/typelevel/shapeless-contrib/issues/33#issuecomment-173910151

> I'm getting a weird behavior in scalacheck while generating `Map[Int, List[Int]]` with an automatically derived `Arbitrary`.

> ```scala
> property("map") = {
>   forAll(implicitly[Arbitrary[Map[Int, List[Int]]]].arbitrary)(ok)
> }
> ```

> Leads to a:

> ```scala
> [info] ! Map.map: Gave up after only 62 passed tests. 312 tests were discarded.
> ```

> Any idea of what's going on here? My quick work around is to generate a `Map[A, B]` from a `List[(A, B)]` (I also have a generalized version to build anything with a `CanBuildFrom` from a `List`):

> ```scala
> implicit def arbitraryMap[A, B]
>   (implicit a: Arbitrary[List[(A, B)]]): Arbitrary[Map[A, B]] =
>     Arbitrary(a.arbitrary.map(_.toMap))
> ```

**Comment by alexarchambault** [comment]
I can't reproduce this error, with both the stable and the snapshot versions of scalacheck-shapeless. scalacheck-shapeless itself doesn't seem to be necessary to get an `Arbitrary[Map[Int, List[Int]]]`... The instances from scalacheck are enough.

**Comment by OlivierBlanvillain** [comment]
Hi, sorry for the late replay, I forgot to push the code on Friday :)

> scalacheck-shapeless itself doesn't seem to be necessary to get an Arbitrary[Map[Int, List[Int]]]

You are right, I didn't realize that. If I add `import org.scalacheck.Arbitrary._` (in addition to `import org.scalacheck.Shapeless._`) everything works as expected. It might be a bit confusing to have stuff compiling but not working, but I guess that intrinsic to the way scala collection / type class derivation interact.

If you are interested I could try to cook up a minimal example where I only import `org.scalacheck.Shapeless._` (these is the setup I'm using: `"org.scalatest" %% "scalatest" % "2.2.5" % "test"`, `"org.scalacheck" %% "scalacheck" % "1.12.5" % "test"`, `"com.github.alexarchambault" %% "scalacheck-shapeless_1.12" % "0.3.1"`).

Thanks for the awesome work and quick feedback!
