### ISSUE TITLE
Shrinking of sealed trait hierarchy never terminates

### ISSUE THREAD

**Issue by cb372** [alexarchambault/scalacheck-shapeless#55]
Hi, thanks for the great library.

I am using scalacheck-shapeless to generate instances of an ADT (sealed trait + case classes/objects). But when a property fails and scalacheck tries to shrink the input, the shrinking continues forever.

Minimal reproduction:

```scala
sealed trait Foo
case object A extends Foo
case object B extends Foo

object Test extends Properties("whatevs") {

  property("failing prop without shrinking") = forAllNoShrink { (x: Foo) =>
    false
  }

  property("failing prop with shrinking") = forAll { (x: Foo) =>
    println(x)
    false
  }

}
```

The `forAllNoShrink` props fails as expected, but the `forAll` one never completes. I can see from the `println` that the original input is `A`, which is then shrunk to `B`, which is then shrunk to `A`, ... *ad infinitum*.

The reproduction is available as a complete sbt project [here](https://github.com/cb372/scalacheck-shapeless-issue).

**Comment by DanielaSfregola** [comment]
Another example of this issue can be found here: https://github.com/DanielaSfregola/random-data-generator/issues/33

**Comment by joroKr21** [comment]
Maybe we should stop shrinking when we find a singleton [here](https://github.com/alexarchambault/scalacheck-shapeless/blob/master/core/shared/src/main/scala/org/scalacheck/derive/MkShrink.scala#L109-L112). Something like this:
```scala
case Inl(h) =>
  if (headSingletons.value().contains(h)) Stream.empty
  else tailSingletons.value().toStream.map(Inr(_)) ++ headShrink.value.shrink(h).map(Inl(_))
case Inr(t) =>
  if (tailSingletons.value().contains(t)) Stream.empty
  else headSingletons.value().toStream.map(Inl(_)) ++ tailShrink.shrink.shrink(t).map(Inr(_))
```
