### ISSUE TITLE
Publish for ScalaCheck 1.14

### ISSUE THREAD

**Issue by LeifW** [alexarchambault/scalacheck-shapeless#86]
It's already that way in master, but there's no published release which supports ScalaCheck 1.14.

**Comment by liff** [comment]
Looks like 1.14 is published for 2.12 but not 2.11.

**Comment by nightscape** [comment]
@LeifW as `"com.github.alexarchambault" %% "scalacheck-shapeless_1.14" % "1.2.0-1"` exists, I guess this can be closed?
